### ISSUE TITLE
Release 1.0.4

### ISSUE THREAD

**Issue by nicoddemus** [EngineeringSoftware/pytest-inline#3]
Hi,

I received notifications that a release 1.0.4 has been uploaded to PyPI, and deleted afterwards.

Some questions just to make sure we are following proper procedure:

1. I believe the correct approach for broken packages is [yanking](https://pypi.org/help/#yanked), never deletion.
2. ~~In general it is strongly recommended for releases to be done via a GH action, never locally, as this gives visibility and source provenance.~~ My bad, I see this has been released via https://github.com/pytest-dev/pytest-inline/actions/workflows/python-publish.yml.

Cheers,

**Comment by sweetStreet** [comment]
Thanks, Bruno! I thought that I could replace an existing package with the
same version as long as I removed the old one. However, I read the doc and
have now learned not to do that in the future.

Thanks!
Yuki

**Comment by nicoddemus** [comment]
Awesome, thanks!

Closing this then.
